//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai già inserito questo indirizzo e-mail!.
        /// </summary>
        internal static string E_mailAlreadyPresent {
            get {
                return ResourceManager.GetString("E-mailAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T: +39 821 39 36 E: shop@materarredamenti.it.
        /// </summary>
        internal static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password non valida..
        /// </summary>
        internal static string InvalidPassword_Error {
            get {
                return ResourceManager.GetString("InvalidPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been locked out, please try again in 10 minutes..
        /// </summary>
        internal static string LockedUser_Error {
            get {
                return ResourceManager.GetString("LockedUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not yet been approved by an administrator..
        /// </summary>
        internal static string NotApprovedUser_Error {
            get {
                return ResourceManager.GetString("NotApprovedUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ti abbiamo già inviato un codice!.
        /// </summary>
        internal static string PromoCodeAlreadySended {
            get {
                return ResourceManager.GetString("PromoCodeAlreadySended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShopTitle.
        /// </summary>
        internal static string ShopTitle {
            get {
                return ResourceManager.GetString("ShopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! L&apos;utente inserito non esiste..
        /// </summary>
        internal static string UnregisteredUser_Error {
            get {
                return ResourceManager.GetString("UnregisteredUser_Error", resourceCulture);
            }
        }
    }
}
